---
title: "setup_13-14_data_with_closure_flags_BG.R"
author: "bgootiiz"
date: "Fri Nov 22 14:07:43 2019"
---

```{r }
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(readr)
library(tidyr)
library(ggplot2)
library(httr)
library(tidyverse)
library(DataExplorer)
library(gridExtra)
library(reshape2)
library(ggcorrplot)
library(glmnet)
library(leaps)  # needed for regsubsets
library(boot) 
#library(ROSE) # needed for oversampling
#library(tidycensus)
```

```{r}
flags_df <- with_flags[, c("NCESSCH","TYPE", "LEVEL","LZIP","UNION", "RECONSTF", "PKOFFRD",  "ULOCAL","FTE","TITLEISTAT", "MAGNET", "CHARTR", "SHARED", "FRELCH", "REDLCH", "AM", "BLACK", "ASIAN", "HISP", "WHITE", "PACIFIC", "TR", "PK", "KG", "G01", "G02", "G03", "G04", "G05", "G06", "G07","G08", "G09","G10", "G11","G12","UG", "MEMBER", "NSLPSTATUS", "closed_any")]

```

```{r}
plot_boxplot(flags_df, by = "closed_any")
```

```{r}
introduce(flags_df)
plot_intro(flags_df)

```

```{r}
plot_bar(flags_df)

```

```{r}

plot_histogram(flags_df)

```

```{r}

plot_boxplot(flags_df, by = "closed_any")

```

```{r}
#Correlation matrix for numeric variables 
nums <- unlist(lapply(flags_df, is.numeric)) 
nums <- flags_df[, nums]

res <- cor(nums)
round(res, 2)

```



